# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

file_stats <- function(filename, sep = '\t', skip = 0L) {
    .Call('covR_file_stats', PACKAGE = 'covR', filename, sep, skip)
}

