# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('covR_rcpp_hello_world', PACKAGE = 'covR')
}

#' @title File input/output
#' @name File input/output
#' 
#' @rdname read_matrix
#' @aliases file_stats
#' 
#' @param filename name of a file
#' @param sep character which delimits columns
#' @param nrows number of rows to read
#' @param skip number of rows to skip
#' @param verbose should verbose output be generated
#' 
#' @return \strong{file_stats} returns a three element vector.
#' 'Total_rows' reports the total number of rows read.
#'  This is either the number of rows in the file or the number of skipped rows and the number of rows read in.
#'  'Rows' is the number of rows read in.
#'  This is either the same as nrows or however many rows were read in after skip and before the end of the file (when less than nrows).
#' 
#' @export
file_stats <- function(filename, sep = '\t', nrows = -1L, skip = 0L, verbose = 1L) {
    .Call('covR_file_stats', PACKAGE = 'covR', filename, sep, nrows, skip, verbose)
}

#' @rdname read_matrix
#' @aliases read_matrix
#' 
#' @param ncols number of columns for the matrix
#' 
#' @return \strong{read_matrix} returns a matrix of strings of dimension specified by nrows and ncols.
#' 
#' @seealso
#' \href{http://cran.r-project.org/web/packages/readr/index.html}{readr}
#' \href{http://cran.r-project.org/web/packages/data.table/index.html}{data.table::fread}
#'
#' @export
read_matrix <- function(filename, sep = '\t', nrows = 1L, ncols = 1L, skip = 0L, verbose = 1L) {
    .Call('covR_read_matrix', PACKAGE = 'covR', filename, sep, nrows, ncols, skip, verbose)
}

